# Generated by Django 4.1.7 on 2023-03-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
    ]
