# Generated by Django 4.1.7 on 2023-03-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
